### ISSUE TITLE
能否给一些初始化数据，让blog正常运行起来？谢谢！！！

### ISSUE THREAD

**Issue by GuoJingFu** [Danyhug/DH-Blog#1]
能否给一些初始化数据，让blog正常运行起来？谢谢！！！

**Comment by Danyhug** [comment]
没想到真有人用😂
目前博客还是初期制作中，很多功能没有开发，基本不可用
后台还在构想只做了基本的功能，甚至没有登录功能😂
---
计划在25年1月基本完成（当做大四的毕设😁）
